version: '3'

services:
  publisher:
    build: ./spring-boot-2-publisher-rest
    container_name: publisher
    ports:
      - "8080:80"
    expose:
      - "80"
    environment:
      - PORT=80
      - RABBIT_HOST=rabbit
      - RABBIT_PORT=5672
      - RABBIT_USER=guest
      - RABBIT_PASS=guest
      - ZIPKIN_BASE_URL=http://zipkin
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - rabbit

  subscriber:
    build: ./spring-boot-2-subscriber-rest
    container_name: subscriber
    expose:
      - "80"
    environment:
      - PORT=80
      - RABBIT_HOST=rabbit
      - RABBIT_PORT=5672
      - RABBIT_USER=guest
      - RABBIT_PASS=guest
      - ZIPKIN_BASE_URL=http://zipkin
      - PUBLISHER_HOST=publisher
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - rabbit

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9412:80"
    expose:
      - "80"
    environment:
      - SERVER_PORT=80

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15673:15672"
    expose:
      - "5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
